#!/bin/bash
#if [ ! -f /etc/samba/smb.conf ]; then

echo -e "search ${SAMBA_REALM}\nnameserver 127.0.0.1" > /etc/resolv.conf

rm -f /etc/samba/smb.conf
    samba-tool domain provision \
  --domain=${SAMBA_DOMAIN} \
  --host-name=${SAMBA_HOST_NAME} \
  --adminpass=${SAMBA_ADMINPASS} \
  --realm=${SAMBA_REALM} \
  --server-role=dc \
  --use-rfc2307 \
  --dns-backend=SAMBA_INTERNAL
#fi
#/usr/sbin/smbd -FSD -d1
#service samba-ad-dc start
