version: '2'

services:

 mysql:
  image: 'mysql:latest'
  domainname: example.com
  hostname: mysql
  networks:
   - devenv
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD="Password1!"
   - MYSQL_USER="example-user"
   - MYSQL_PASSWORD="my-secret-pw"
   - MYSQL_DATABASE="example-database"
# ports:
#  - '3306:3306'
  volumes_from:
   - mysqldata

 mysqldata:
  build: mysql-data
 
 postgresql:
  image: 'postgres:latest'
  domainname: example.com
  hostname: postgresql
  networks:
   - devenv
  restart: always
  environment:
   - POSTGRES_PASSWORD=Password1!
   - POSTGRES_USER=root
   - POSTGRES_DB=example-database
# ports:
#  - '5432:5432'
  volumes_from:
   - postgresqldata

 postgresqldata:
  build: postgresql-data

 git:
  build: git
  domainname: example.com
  hostname: git
  networks:
   - devenv
  volumes_from:
   - gitdata
  ports:
   - "2222:22"
  restart: always

 gitdata:
  build: git-data

 jenkins:
  image: jenkins:2.0-beta-1
  domainname: example.com
  hostname: jenkins
  networks:
   - devenv
  restart: always
  volumes_from:
   - jenkinsdata
  ports:
#  - "8080:8080"
   - "50000:50000"

 jenkinsdata:
  build: jenkins-data

 gitlab:
  image: 'gitlab/gitlab-ce:latest'
  domainname: example.com
  hostname: gitlab
  networks:
   - devenv
  restart: always
  environment:
   GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab.example.com'
    gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
#  - '80:80'
   - '2224:22'
  volumes_from:
   - gitlabdata

 gitlabdata:
  build: gitlab-data

 nginx:
  build: nginx
  domainname: example.com
  hostname: nginx
  networks:
   - devenv
  volumes_from:
   - nginxdata
  ports:
   - "80:80"
   - "443:443"
  restart: always

 nginxdata:
  build: nginx-data

 ldapaccountmanager:
  build: ldap-account-manager
  domainname: example.com
  hostname: ldapaccountmanager
  networks:
   - devenv
  restart: always
# ports:
#  - "80:80"

#samba:
# build: samba-ad-dc
# volumes_from:
#  - sambadata
# privileged: true
# restart: always
# ports:
#  - '53:53'
#  - '88:88'
#  - '135:135'
#  - '137:137'
#  - '138:138'
#  - '139:139'
#  - '389:389'
#  - '445:445'
#  - '464:464'
#  - '636:636'
#  - '3268:3268'
#  - '3269:3269'

# environment:
#  SAMBA_DOMAIN: "samba"
#  SAMBA_REALM: "example.com"
#  SAMBA_PASSWORD: "Password1!"
#  SAMBA_DNS_FORWARDER: "8.8.8.8"
#  workgroup: "workgroup"

#sambadata:
# build: samba-data

 openldap:
  image: osixia/openldap
  domainname: example.com
  hostname: openldap
  networks:
   - devenv
  volumes_from:
   - openldapdata
  restart: always
  ports:
   - '389:389'
   - '636:636'
  environment:
   LDAP_DOMAIN: "example.com"
   LDAP_BASE_DN: "dc=example,dc=com"
   LDAP_ADMIN_PASSWORD: "Password1!"
   LDAP_CONFIG_PASSWORD: "Password1!"

 openldapdata:
  build: openldap-data

 ldapadmin:
  image: osixia/phpldapadmin
  domainname: example.com
  hostname: ldapadmin
  networks:
   - devenv
  restart: always
  environment:
   PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,dc=example,dc=com'}]}]}]"

######

networks:
 devenv:

