jenkins:
 image: jenkins
 volumes_from:
  - jenkinsdata
 ports:
  - "8080:8080"
  - "50000:50000"

jenkinsdata:
 build: jenkins-data

gitlab:
 image: 'gitlab/gitlab-ce:latest'
 restart: always
 hostname: 'gitlab.example.com'
 environment:
  GITLAB_OMNIBUS_CONFIG: |
   external_url 'https://gitlab.example.com'
   gitlab_rails['gitlab_shell_ssh_port'] = 2224
 ports:
#  - '80:80'
#  - '443:443'
  - '2224:22'
 volumes_from:
  - gitlabdata

gitlabdata:
 build: gitlab-data

nginx:
 build: nginx
 ports:
  - "80:80"
 restart: always
 links:
  - jenkins:jenkins
  - gitlab:gitlab
  - ldapaccountmanager:ldapaccountmanager

ldapaccountmanager:
 build: ldap-account-manager
# ports:
#  - "80:80"

samba:
 build: samba
 volumes_from:
  - sambadata
 restart: always
 ports:
  - '53:53'
  - '88:88'
  - '135:135'
  - '137:137'
  - '138:138'
  - '139:139'
  - '389:389'
  - '445:445'
  - '464:464'
  - '636:636'
  - '1024-1050:1024-1050'
  - '3268:3268'
  - '3269:3269'

 environment:
  workgroup: "workgroup"

sambadata:
 build: samba-data
