version: '2'

services:

 mysql:
  image: 'mysql:latest'
  hostname: 'mysql.example.com'
  networks:
   - devenv
  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD="Password1!"
   - MYSQL_USER="example-user"
   - MYSQL_PASSWORD="my-secret-pw"
   - MYSQL_DATABASE="example-database"
# ports:
#  - '3306:3306'
  volumes_from:
   - mysqldata

 mysqldata:
  build: mysql-data
 
 postgresql:
  image: 'postgres:latest'
  hostname: 'postgresql.example.com'
  networks:
   - devenv
  restart: always
  environment:
   - POSTGRES_PASSWORD=Password1!
   - POSTGRES_USER=root
   - POSTGRES_DB=example-database
# ports:
#  - '5432:5432'
  volumes_from:
   - postgresqldata

 postgresqldata:
  build: postgresql-data

 jenkins:
  image: jenkins:2.0-beta-1
  hostname: 'jenkins.example.com'
  networks:
   - devenv
  restart: always
  volumes_from:
   - jenkinsdata
  ports:
#  - "8080:8080"
   - "50000:50000"

 jenkinsdata:
  build: jenkins-data

 gitlab:
  image: 'gitlab/gitlab-ce:latest'
  hostname: 'gitlab.example.com'
  networks:
   - devenv
  restart: always
  environment:
   GITLAB_OMNIBUS_CONFIG: |
    external_url 'https://gitlab.example.com'
    gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
#  - '80:80'
   - '2224:22'
  volumes_from:
   - gitlabdata

 gitlabdata:
  build: gitlab-data

 nginx:
  build: nginx
  hostname: 'nginx.example.com'
  networks:
   - devenv
  volumes_from:
   - nginxdata
  ports:
   - "80:80"
  restart: always

 nginxdata:
  build: nginx-data

 ldapaccountmanager:
  build: ldap-account-manager
  hostname: 'ldapaccountmanager.example.com'
  networks:
   - devenv
# ports:
#  - "80:80"

#samba:
# build: samba-ad-dc
# volumes_from:
#  - sambadata
# privileged: true
# restart: always
# ports:
#  - '53:53'
#  - '88:88'
#  - '135:135'
#  - '137:137'
#  - '138:138'
#  - '139:139'
#  - '389:389'
#  - '445:445'
#  - '464:464'
#  - '636:636'
#  - '3268:3268'
#  - '3269:3269'

# environment:
#  SAMBA_DOMAIN: "samba"
#  SAMBA_REALM: "example.com"
#  SAMBA_PASSWORD: "Password1!"
#  SAMBA_DNS_FORWARDER: "8.8.8.8"
#  workgroup: "workgroup"

#sambadata:
# build: samba-data

 openldap:
  image: dinkel/openldap
  hostname: 'ldap.example.com'
  networks:
   - devenv
  volumes_from:
   - openldapdata
  restart: always
  ports:
   - '389:389'

  environment:
   SLAPD_DOMAIN: "ldap.example.com"
   SLAPD_PASSWORD: "Password1!"
#  SLAPD_CONFIG_PASSWORD: "Password1!"
#  SLAPD_ORGANIZATION: "Example com"
   SLAPD_ADDITIONAL_SCHEMAS: "openldap,misc"
   SLAPD_ADDITIONAL_MODULES: "memberof"

 openldapdata:
  build: openldap-data


networks:
 devenv:

