mysql:
 image: 'mysql:latest'
 restart: always
 hostname: 'mysql.example.com'
 environment:
  - MYSQL_ROOT_PASSWORD="my-secret-pw"
  - MYSQL_USER="example-user"
  - MYSQL_PASSWORD="my-secret-pw"
  - MYSQL_DATABASE="example-database"
 ports:
  - '3306:3306'
 volumes_from:
  - mysqldata

mysqldata:
 build: mysql-data

postgresql:
 image: 'postgres:latest'
 restart: always
 hostname: 'postgresql.example.com'
 environment:
  - POSTGRES_PASSWORD="my-secret-pw"
  - POSTGRES_USER="example-user"
  - POSTGRES_DB="example-database"
 ports:
  - '5432:5432'
 volumes_from:
  - postgresqldata

postgresqldata:
 build: postgresql-data

jenkins:
 image: jenkins
 volumes_from:
  - jenkinsdata
 ports:
  - "8080:8080"
  - "50000:50000"

jenkinsdata:
 build: jenkins-data

gitlab:
 image: 'gitlab/gitlab-ce:latest'
 restart: always
 hostname: 'gitlab.example.com'
 environment:
  GITLAB_OMNIBUS_CONFIG: |
   external_url 'https://gitlab.example.com'
   gitlab_rails['gitlab_shell_ssh_port'] = 2224
 ports:
#  - '80:80'
#  - '443:443'
  - '2224:22'
 volumes_from:
  - gitlabdata

gitlabdata:
 build: gitlab-data

nginx:
 build: nginx
 volumes_from:
  - nginxdata
 ports:
  - "80:80"
 restart: always
 links:
  - jenkins:jenkins
  - gitlab:gitlab
  - ldapaccountmanager:ldapaccountmanager

nginxdata:
 build: nginx-data

ldapaccountmanager:
 build: ldap-account-manager
# ports:
#  - "80:80"

samba:
 build: samba
 volumes_from:
  - sambadata
 restart: always
 ports:
  - '53:53'
  - '88:88'
  - '135:135'
  - '137:137'
  - '138:138'
  - '139:139'
  - '389:389'
  - '445:445'
  - '464:464'
  - '636:636'
  - '1024-1050:1024-1050'
  - '3268:3268'
  - '3269:3269'

 environment:
  workgroup: "workgroup"

sambadata:
 build: samba-data
