FROM jenkins
USER root
RUN apt-get update
RUN apt-get install -y clang cmake doxygen doxygen-latex graphviz libboost-all-dev libpoco-dev libopencv-dev qt5-default qttools5-dev  g++ libsqlite3-dev
USER jenkins
